---
- name: Template .env file for miniflux
  ansible.builtin.template:
    src: env.j2
    dest: "{{ role_path }}/files/.env"

- name: Deploy miniflux container via Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ role_path }}/files"
    state: present

- name: Clean up .env file
  ansible.builtin.file:
    path: "{{ role_path }}/files/.env"
    state: absent
