services:
 uptime-kuma:
   image: louislam/uptime-kuma
   container_name: uptime-kuma
   volumes:
     - /DATA/AppData/Uptime-Kuma:/app/data
     - /var/run/docker.sock:/var/run/docker.sock
   ports:
     - "3001:3001"
   restart: always
   labels:
     - "docktail.service.enable=true"
     - "docktail.service.name=uptime"
     - "docktail.service.port=3001"
     - "docktail.service.protocol=http"
     - "docktail.service.service-port=80"
     - "docktail.service.service-protocol=http"
