# Thinkmini Variables

target_branch: testing # Specify which branch to target with this host.

# Specify the tailnet for the device
tailnet_domain: samplayskeys.ts.net

# Include the containers to install on this machine
containers:
  - docktail
  - miniflux_scaletail
  - tsflow
  - uptimekuma
  - tailbench
  - arr-suite
  - arcane
  - forgejo
  - mealie.io
  - plex
  - rahoot
  - signal
  - syncthing
