all:
  hosts:
    nuclet:
      ansible_connection: local
    thinkmini:
      ansible_host: thinkmini.samplayskeys.ts.net
    oracle1:
      ansible_host: oracle1.samplayskeys.ts.net

  children:
    homelab:
      hosts:
        nuclet:

    inactive_hosts:
      hosts:
       thinkmini:
       oracle1:
