services:
    transmission:
        image: lscr.io/linuxserver/transmission
        restart: always
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=America/New_York
            - TRANSMISSION_WEB_HOME=${TRANSMISSION_WEB_HOME}
        volumes:
            - ${DATA_PATH}/transmission:/config
            - ${DATA_PATH}/downloads:/downloads
            - ${DATA_PATH}/watch:/watch
        ports:
            - '${PORT_FLOOD}:9091'
            - 51413:51413
            - 51413:51413/udp
        cap_add:
            - NET_ADMIN

    radarr:
        image: linuxserver/radarr
        restart: always
        ports:
            - '${PORT_RADARR}:7878'
        environment:
            - PGID=${GID}
            - PUID=${UID}
        volumes:
            - ${DATA_PATH}/radarr:/config
            - ${DATA_PATH}/movies:/movies
            - ${DATA_PATH}/downloads:/downloads

    sonarr:
        image: linuxserver/sonarr
        restart: always
        ports:
            - '${PORT_SONARR}:8989'
        environment:
            - PGID=${GID}
            - PUID=${UID}
        volumes:
            - ${DATA_PATH}/sonarr:/config
            - ${DATA_PATH}/tv:/tv
            - ${DATA_PATH}/downloads:/downloads
      
    prowlarr:
        image: linuxserver/prowlarr
        restart: always
        ports:
            - '${PORT_PROWLARR}:9696'
        cap_add:
            - NET_ADMIN
        environment:
            - PGID=${GID}
            - PUID=${UID}
        volumes:
            - ${DATA_PATH}/prowlarr:/config
            - ${DATA_PATH}/watch:/downloads # transmission watch directory
            - /etc/localtime:/etc/localtime:ro
            
    flaresolverr:
        # DockerHub mirror flaresolverr/flaresolverr:latest
        image: ghcr.io/flaresolverr/flaresolverr:latest
        container_name: flaresolverr
        environment:
            - LOG_LEVEL=${LOG_LEVEL:-info}
            - LOG_HTML=${LOG_HTML:-false}
            - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
            - TZ=America/New_York
        ports:
            - "8191:8191"
        restart: unless-stopped 
